language: node_js
node_js:
  - 0.10
before_script:
  - npm install -g grunt-cli
  - npm install -g bower
  - grunt --version
  - bower --version
  - bower install
script: npm test
notifications:
  email:
    - github@pinemz.net